import { RouterView } from "vue-router";


const routerItems = [
  {
    path: "/login",
    name: "Login",
    component: () => import("../views/Login.vue"),
    meta: { title: "登录" },
  },
  {
    path: "/",
    component: () => import("../layout/index.vue"),
    children: [
      {
        path: "",
        name: "Home",
        component: () => import("../views/Home.vue"),
        meta: { title: "menu.home", icon: "House" },
      },
      {
        path: "/base",
        name: "Base",
        component: RouterView,
        meta: { title: "menu.base", icon: "Operation" },
        children: [
          {
            path: "/entities",
            name: "BaseEntities",
            component: () => import("../views/base/entities.vue"),
            meta: { title: "menu.baseEntities", icon: "DataBoard" },
            img: "baseEntities.png",
          },
          {
            path: "/position",
            name: "BasePosition",
            component: () => import("../views/base/position.vue"),
            meta: { title: "menu.basePosition", icon: "DataBoard" },
            img: "basePosition.png",
          },
          {
            path: "/fly",
            name: "BaseFly",
            component: () => import("../views/base/fly.vue"),
            meta: { title: "menu.baseFly", icon: "DataBoard" },
            img: "baseFly.png",
          },
          {
            path: "/sport",
            name: "BaseSport",
            component: () => import("../views/base/sport.vue"),
            meta: { title: "menu.baseSport", icon: "DataBoard" },
            img: "baseSport.png",
          },
          {
            path: "/tip",
            name: "BaseTip",
            component: () => import("../views/base/tip.vue"),
            meta: { title: "menu.baseTip", icon: "DataBoard" },
            img: "baseTip.png",
          },
          {
            path: "/mask",
            name: "BaseMask",
            component: () => import("../views/base/mask.vue"),
            meta: { title: "menu.baseMask", icon: "DataBoard" },
            img: "baseMask.png",
          },
          {
            path: "/loadShp",
            name: "BaseLoadShp",
            component: () => import("../views/base/loadShp.vue"),
            meta: { title: "menu.baseLoadShp", icon: "DataBoard" },
            img: "baseLoadShp.png",
          },
          {
            path: "/loadMVT",
            name: "BaseLoadMVT",
            component: () => import("../views/base/loadMVT.vue"),
            meta: { title: "menu.baseLoadMVT", icon: "DataBoard" },
            img: "baseLoadMVT.png",
          },
          {
            path: "/zoomControl",
            name: "BaseZoomControl",
            component: () => import("../views/base/zoomControl.vue"),
            meta: { title: "menu.baseZoomControl", icon: "DataBoard" },
            img: "baseZoomControl.png",
          },
          {
            path: "/transparent",
            name: "BaseTransparent",
            component: () => import("../views/base/transparent.vue"),
            meta: { title: "menu.baseTransparent", icon: "DataBoard" },
            img: "baseTransparent.png",
          },
          {
            path: "/flyCircle",
            name: "BaseFlyCircle",
            component: () => import("../views/base/flyCircle.vue"),
            meta: { title: "menu.baseFlyCircle", icon: "DataBoard" },
            img: "baseFlyCircle.png",
          },
        ],
      },
      {
        path: "/layers",
        name: "Layers",
        component: RouterView,
        meta: { title: "menu.baseLayers", icon: "MapLocation" },
        children: [
          {
            path: "/singleImage",
            name: "LayerSingleImage",
            component: () => import("../views/layers/singleImage.vue"),
            meta: { title: "menu.layersPicture", icon: "Picture" },
            img: "layersPicture.png",
          },
          {
            path: "/xyz",
            name: "LayerXYZ",
            component: () => import("../views/layers/xyz.vue"),
            meta: { title: "menu.layersXYZ", icon: "DataBoard" },
            img: "layersXYZ.png",
          },
          {
            path: "/tms",
            name: "LayerTMS",
            component: () => import("../views/layers/tms.vue"),
            meta: { title: "menu.layersTMS", icon: "DataBoard" },
            img: "layersTMS.png",
          },
          {
            path: "/wms",
            name: "LayerWMS",
            component: () => import("../views/layers/wms.vue"),
            meta: { title: "menu.layersWMS", icon: "DataBoard" },
            img: "layersWMS.png",
          },
          {
            path: "/wmts",
            name: "LayerWMTS",
            component: () => import("../views/layers/wmts.vue"),
            meta: { title: "menu.layersWMTS", icon: "DataBoard" },
            img: "layersWMTS.png",
          },
          {
            path: "/tdt",
            name: "LayerTDT",
            component: () => import("../views/layers/tdt.vue"),
            meta: { title: "menu.layersTDT", icon: "DataBoard" },
            img: "layersTDT.png",
          },
          {
            path: "/cgcs4490",
            name: "Layer4490",
            component: () => import("../views/layers/epsg4490.vue"),
            meta: { title: "menu.layers4490", icon: "DataBoard" },
            img: "layers4490.png",
          },
          {
            path: "/amap",
            name: "LayerAmap",
            component: () => import("../views/layers/addAmap.vue"),
            meta: { title: "menu.layersAmap", icon: "DataBoard" },
            img: "layersAmap.png",
          },
          {
            path: "/mapbox",
            name: "LayerMKT",
            component: () => import("../views/layers/mapbox.vue"),
            meta: { title: "menu.layersMapbox", icon: "DataBoard" },
            img: "layersMapbox.png",
          },
          {
            path: "/dynamicMap",
            name: "LayerDynamicMap",
            component: () => import("../views/layers/dynamicMap.vue"),
            meta: { title: "menu.layersDynamicMap", icon: "DataBoard" },
            img: "layersDynamicMap.png",
          },
          {
            path: "/offlineTerrain",
            name: "LayerOfflineTerrain",
            component: () => import("../views/layers/offlineTerrain.vue"),
            meta: { title: "menu.layersOfflineTerrain", icon: "DataBoard" },
            img: "layersOfflineTerrain.png",
          },
        ],
      },

      {
        path: "/elements",
        name: "Elements",
        component: RouterView,
        meta: { title: "menu.elements", icon: "Grid" },
        children: [
          {
            path: "/basicEntities",
            name: "ElementBasicEntities",
            component: () => import("../views/elements/basicEntities.vue"),
            meta: { title: "menu.elementBasicEntities", icon: "DataBoard" },
            img: "elementBasicEntities.png",
          },
          {
            path: "/billboard",
            name: "ElementBillboard",
            component: () => import("../views/elements/billboard.vue"),
            meta: { title: "menu.elementBillboard", icon: "DataBoard" },
            img: "elementBillboard.png",
          },
          {
            path: "/massiveBillboards",
            name: "ElementMassiveBillboards",
            component: () => import("../views/elements/massiveBillboards.vue"),
            meta: { title: "menu.elementMassiveBillboards", icon: "DataBoard" },
            img: "elementMassiveBillboards.png",
          },
          {
            path: "/popup",
            name: "ElementPopup",
            component: () => import("../views/elements/popup.vue"),
            meta: { title: "menu.elementPopup", icon: "DataBoard" },
            img: "elementPopup.png",
          },
          {
            path: "/geojson",
            name: "ElementGeoJson",
            component: () => import("../views/elements/geoJson.vue"),
            meta: { title: "menu.elementGeoJson", icon: "DataBoard" },
            img: "elementGeoJson.png",
          },
          {
            path: "/primitive",
            name: "ElementPrimitive",
            component: () => import("../views/elements/primitiveGeometry.vue"),
            meta: { title: "menu.elementPrimitive", icon: "DataBoard" },
            img: "elementPrimitive.png",
          },
          {
            path: "/collection",
            name: "ElementCollection",
            component: () => import("../views/elements/entityCollection.vue"),
            meta: { title: "menu.elementEntityCollection", icon: "DataBoard" },
            img: "elementEntityCollection.png",
          },
          {
            path: "/events",
            name: "ElementEvents",
            component: () => import("../views/elements/events.vue"),
            meta: { title: "menu.elementEvents", icon: "DataBoard" },
            img: "elementEvents.png",
          },
          {
            path: "/svg",
            name: "ElementSVG",
            component: () => import("../views/elements/svg.vue"),
            meta: { title: "menu.elementSVG", icon: "DataBoard" },
            img: "elementSVG.png",
          },
          {
            path: "/gif",
            name: "ElementGIF",
            component: () => import("../views/elements/gif.vue"),
            meta: { title: "menu.elementGIF", icon: "DataBoard" },
            img: "elementGIF.png",
          },
          {
            path: "/clustering",
            name: "ElementClustering",
            component: () => import("../views/elements/clustering.vue"),
            meta: { title: "menu.elementClustering", icon: "DataBoard" },
            img: "elementClustering.png",
          },
          {
            path: "/czml",
            name: "ElementCZML",
            component: () => import("../views/elements/czml.vue"),
            meta: { title: "menu.elementCZML", icon: "DataBoard" },
            img: "elementCZML.png",
          },
        ],
      },
      {
        path: "/particle",
        name: "Particle",
        meta: { title: "menu.particle", icon: "MagicStick" },
        children: [
          {
            path: "/particleExamples",
            name: "ParticleExamples",
            component: () =>
              import("../views/particleEffect/particleExamples.vue"),
            meta: { title: "menu.particleExamples", icon: "DataBoard" },
            img: "particleExamples.png",
          },
        ],
      },
      {
        path: "/models",
        name: "Models",
        component: RouterView,
        meta: { title: "menu.models", icon: "Box" },
        children: [
          {
            path: "/loadModel",
            name: "ModelLoad",
            component: () => import("../views/models/loadModel.vue"),
            meta: { title: "menu.modelLoad", icon: "DataBoard" },
            img: "modelLoad.png",
          },
          {
            path: "/primitiveModel",
            name: "ModelPrimitive",
            component: () => import("../views/models/primitiveModel.vue"),
            meta: { title: "menu.modelPrimitive", icon: "DataBoard" },
            img: "modelPrimitive.png",
          },
          {
            path: "/primitiveMassive",
            name: "ModelPrimitiveMassive",
            component: () => import("../views/models/primitiveMassive.vue"),
            meta: { title: "menu.modelPrimitiveMassive", icon: "DataBoard" },
            img: "modelPrimitiveMassive.png",
          },
          {
            path: "/interpolation",
            name: "ModelInterpolation",
            component: () => import("../views/models/interpolation.vue"),
            meta: { title: "menu.modelInterpolation", icon: "DataBoard" },
            img: "modelInterpolation.png",
          },
          {
            path: "/info",
            name: "ModelInfo",
            component: () => import("../views/models/modelInfo.vue"),
            meta: { title: "menu.modelInfo", icon: "DataBoard" },
            img: "modelInfo.png",
          },
          {
            path: "/windTurbine",
            name: "ModelWindTurbine",
            component: () => import("../views/models/windTurbine.vue"),
            meta: { title: "menu.modelWindTurbine", icon: "DataBoard" },
            img: "modelWindTurbine.png",
          },
        ],
      },
      {
        path: "/3dtiles",
        name: "3DTiles",
        component: RouterView,
        meta: { title: "menu.3dtiles", icon: "Collection" },
        children: [
          {
            path: "/texture",
            name: "Texture3DTiles",
            component: () => import("../views/3dtiles/texture3dtiles.vue"),
            meta: { title: "menu.texture3dtiles", icon: "DataBoard" },
            img: "texture3dtiles.png",
          },
          {
            path: "/modelInfo",
            name: "ModelInfo3DTiles",
            component: () => import("../views/3dtiles/modelInfo3dtiles.vue"),
            meta: { title: "menu.modelInfo3dtiles", icon: "DataBoard" },
            img: "modelInfo3dtiles.png",
          },
        ],
      },
      {
        path: "/measurement",
        name: "Measurement",
        component: RouterView,
        meta: { title: "menu.measurement", icon: "Aim" },
        children: [
          {
            path: "/measurementTools",
            name: "MeasurementTools",
            component: () => import("../views/measurement/measurement.vue"),
            meta: { title: "menu.measurementTools", icon: "DataBoard" },
            img: "measurementTools.png",
          },
        ],
      },
      {
        path: "/effects",
        name: "Effects",
        component: RouterView,
        meta: { title: "menu.effects", icon: "Tools" },
        children: [
          {
            path: "/flowLine",
            name: "EffectFlowLine",
            component: () => import("../views/effects/flowLine.vue"),
            meta: { title: "menu.flowLine", icon: "DataBoard" },
            img: "flowLine.png",
          },
          {
            path: "/radarScan",
            name: "EffectRadarScan",
            component: () => import("../views/effects/radarScan.vue"),
            meta: { title: "menu.radarScan", icon: "DataBoard" },
            img: "radarScan.png",
          },
          {
            path: "/waterRipple",
            name: "EffectWaterRipple",
            component: () => import("../views/effects/waterRipple.vue"),
            meta: { title: "menu.waterRipple", icon: "DataBoard" },
            img: "waterRipple.png",
          },
          {
            path: "/diffusionPoint",
            name: "EffectDiffusionPoint",
            component: () => import("../views/effects/diffusionPoint.vue"),
            meta: { title: "menu.diffusionPoint", icon: "DataBoard" },
            img: "diffusionPoint.png",
          },
          {
            path: "/electronicFence",
            name: "EffectElectronicFence",
            component: () => import("../views/effects/electronicFence.vue"),
            meta: { title: "menu.electronicFence", icon: "DataBoard" },
            img: "electronicFence.png",
          },
          {
            path: "/electronicFence2",
            name: "EffectElectronicFence2",
            component: () => import("../views/effects/electronicFence2.vue"),
            meta: { title: "menu.electronicFence2", icon: "DataBoard" },
            img: "electronicFence2.png",
          },
          {
            path: "/movingCone",
            name: "EffectMovingCone",
            component: () => import("../views/effects/movingCone.vue"),
            meta: { title: "menu.movingCone", icon: "DataBoard" },
            img: "movingCone.png",
          },
          {
            path: "/movingFrustum",
            name: "EffectMovingFrustum",
            component: () => import("../views/effects/movingFrustum.vue"),
            meta: { title: "menu.movingFrustum", icon: "DataBoard" },
            img: "movingFrustum.png",
          },
          {
            path: "/pointLight",
            name: "EffectPointLight",
            component: () => import("../views/effects/pointLight.vue"),
            meta: { title: "menu.pointLight", icon: "DataBoard" },
            img: "pointLight.png",
          },

          {
            path: "/cityFlow",
            name: "EffectCityFlow",
            component: () => import("../views/effects/cityFlow.vue"),
            meta: { title: "menu.cityFlow", icon: "DataBoard" },
            img: "cityFlow.png",
          },
        ],
      },
      {
        path: "/skyBox",
        name: "EffectSkyBox",
        meta: { title: "天空盒", icon: "Sunny" },
        children: [
          {
            path: "/baseSkyBox",
            name: "BaseSkyBox",
            component: () => import("../views/skyBox/baseSkyBox.vue"),
            meta: { title: "menu.baseSkyBox", icon: "Sunny" },
            img: "baseSkyBox.png",
          },
          {
            path: "/nearEarth",
            name: "NearEarthSkyBox",
            component: () => import("../views/skyBox/nearEarthSkyBox.vue"),
            meta: { title: "menu.nearEarthSkyBox", icon: "Sunny" },
            img: "nearEarthSkyBox.png",
          },
          {
            path: "/groundSkyBox",
            name: "GroundSkyBox",
            component: () => import("../views/skyBox/groundSkyBox.vue"),
            meta: { title: "menu.groundSkyBox", icon: "Sunny" },
            img: "groundSkyBox.png",
          },
        ],
      },
    ],
  },
];

export default routerItems;
